<?php

/**
 * Razy Framework — PHAR Build Script
 *
 * Builds Razy.phar from the src/ directory and optionally copies it to
 * one or more target paths.
 *
 * Usage:
 *   php build.php [path1] [path2] ...
 *
 * Examples:
 *   php build.php                                  # Build Razy.phar in project root
 *   php build.php /var/www/mysite                  # Build and copy to /var/www/mysite/Razy.phar
 *   php build.php ./site-a ./site-b ../staging     # Build and copy to multiple locations
 */

try {
    $pharFile = 'Razy.phar';

    // clean up
    if (file_exists($pharFile)) {
        unlink($pharFile);
    }

    if (file_exists($pharFile . '.gz')) {
        unlink($pharFile . '.gz');
    }

    // create phar
    $phar = new Phar($pharFile);

    // start buffering. Mandatory to modify stub to add shebang
    $phar->startBuffering();

    // Create the default stub from main.php entrypoint
    $defaultStub = $phar->createDefaultStub('main.php');

    // Add the rest of the apps files
    $phar->buildFromDirectory(__DIR__ . '/src');

    // COMPILE-ON-DEPLOY M1: bake a class => file map for the library tree.
    // At runtime the autoloader answers the first lookup from this map (one
    // array hit instead of is_dir + up to 3 is_file probes over the phar
    // stream — the single biggest per-request boot bucket, profiled 2026-09).
    // A map miss falls through to the exact legacy probe ladder, and a map
    // entry whose include fails to define the class ALSO falls through, so
    // the map can only ever make a hit faster, never an answer wrong.
    $classmap = [];
    $libRoot = str_replace('\\', '/', realpath(__DIR__ . '/src/library')) . '/';
    $libDir = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator(__DIR__ . '/src/library', FilesystemIterator::SKIP_DOTS)
    );
    foreach ($libDir as $file) {
        if (!$file->isFile() || 'php' !== $file->getExtension()) {
            continue;
        }
        $src = file_get_contents($file->getPathname());
        if (!preg_match('/^\s*namespace\s+([^\s;]+)/m', $src, $ns)) {
            continue;
        }
        $namespace = trim($ns[1]);
        if (preg_match_all('/^\s*(?:(?:final|abstract|readonly)\s+)*(?:class|interface|trait|enum)\s+([A-Za-z_]\w*)/m', $src, $types)) {
            $relative = substr(str_replace('\\', '/', realpath($file->getPathname())), strlen($libRoot));
            foreach ($types[1] as $type) {
                // First declaration wins per FQCN (duplicate class = fatal in
                // PHP anyway; the probe ladder would resolve the convention
                // path either way)
                $classmap[$namespace . '\\' . $type] ??= $relative;
            }
        }
    }
    ksort($classmap);
    $mapPhp = "<?php\n\n/**\n * Baked classmap — generated by build.php at phar build time. Never edit.\n * Count: " . count($classmap) . " classes.\n */\n\nreturn " . var_export($classmap, true) . ";\n";
    $phar->addFromString('system/classmap.php', $mapPhp);
    echo "classmap: " . count($classmap) . " classes baked" . PHP_EOL;

    // Customize the stub to add the shebang
    $stub = "#!/usr/bin/env php \n" . $defaultStub;

    // Add the stub
    $phar->setStub($stub);

    $phar->stopBuffering();

    // plus - compressing it into gzip
    $phar->compressFiles(Phar::GZ);

    # Make the file executable
    if (PHP_OS_FAMILY !== 'Windows') {
        chmod(__DIR__ . '/' . $pharFile, 0770);
    }

    echo "$pharFile successfully created" . PHP_EOL;

    // Copy to target paths passed as CLI arguments
    $targets = array_slice($argv, 1);
    foreach ($targets as $target) {
        $target = rtrim($target, '/\\');
        if (!is_dir($target)) {
            echo "  [SKIP] Directory does not exist: $target" . PHP_EOL;
            continue;
        }
        $dest = $target . DIRECTORY_SEPARATOR . $pharFile;
        if (copy(__DIR__ . '/' . $pharFile, $dest)) {
            echo "  [OK]   Copied to $dest" . PHP_EOL;
        } else {
            echo "  [FAIL] Could not copy to $dest" . PHP_EOL;
        }
    }
} catch (Exception $e) {
    echo $e->getMessage();
}
