# Caddyfile — Generated by Razy Framework
# Do not edit manually; regenerate with: php Razy.phar rewrite --caddy

{
	frankenphp
	order php_server before file_server
}

<!-- START BLOCK: site -->
{$domain} {
	root * {$document_root}

<!-- START BLOCK: webassets -->
	# Webassets: {$mapping}
	@webasset_{$mapping_id} path /{$route_path}webassets/{$mapping}/*
	handle @webasset_{$mapping_id} {
		uri strip_prefix /{$route_path}webassets/{$mapping}
		root * {$container_path}
		file_server
	}
<!-- END BLOCK: webassets -->
<!-- START BLOCK: data_mapping -->
	# Data mapping: {$dist_code}
	@data_{$data_id} path /{$route_path}data/*
	handle @data_{$data_id} {
		uri strip_prefix /{$route_path}data
		root * {$data_path}
		file_server
	}
<!-- END BLOCK: data_mapping -->
<!-- START BLOCK: shared -->
	# Shared modules
	@shared path /*/shared/*
	handle @shared {
		root * {$document_root}
		uri replace /shared/ /shared/ 1
		file_server
	}
<!-- END BLOCK: shared -->
<!-- START BLOCK: worker -->
	php_server {
		worker {$document_root}/index.php
	}
<!-- END BLOCK: worker -->
<!-- START BLOCK: standard -->
	php_server
<!-- END BLOCK: standard -->
}

<!-- END BLOCK: site -->
