# Caddyfile — Generated by Razy Framework
# Do not edit manually; regenerate with: php Razy.phar rewrite --caddy

{
	frankenphp
	order php_server before file_server
}

<!-- START BLOCK: site -->
{$domain} {
	root * {$document_root}

<!-- START BLOCK: webassets -->
	# Webassets: {$mapping}
	@webasset_{$mapping_id} path /{$route_path}webassets/{$mapping}/*
	handle @webasset_{$mapping_id} {
		uri strip_prefix /{$route_path}webassets/{$mapping}
		root * {$container_path}
		file_server
	}
<!-- END BLOCK: webassets -->
<!-- START BLOCK: data_mapping -->
	# Data mapping: {$dist_code}
	@data_{$data_id} path /{$route_path}data/*
	handle @data_{$data_id} {
		uri strip_prefix /{$route_path}data
		root * {$data_path}
		file_server
	}
<!-- END BLOCK: data_mapping -->
<!-- START BLOCK: shared -->
	# Shared modules
	@shared path /*/shared/*
	handle @shared {
		root * {$document_root}
		uri replace /shared/ /shared/ 1
		file_server
	}
<!-- END BLOCK: shared -->
<!-- START BLOCK: exclusion -->
	# Declared sibling paths (sites.inc.php 'exclude_paths') — never claimed by Razy.
	# php_server is gated on @not_excluded, so these paths are served statically if
	# present or 404; proxying them belongs to the edge config (this file stays do-not-claim).
	@not_excluded not path {$path_patterns}
<!-- END BLOCK: exclusion -->
<!-- START BLOCK: php_claim -->
	# Claim scoping (coexistence Phase 2, Caddy side of Apache's per-mount
	# route_path discipline): the PHP claim covers ONLY the mounted prefixes
	# below; declared sibling exclusions stay outside it inside this matcher.
	{$matcher_body}
<!-- END BLOCK: php_claim -->
<!-- START BLOCK: health -->
	# Health probe (FM-5): on sub-path mounts the scoped claim would strand
	# /_razy/health, so it gets its own handle FIRST (pattern follows
	# deploy/Caddyfile — answer to Q5). Standard php_server on purpose: probes
	# are answered pre-dispatch and never need the app worker.
	handle /_razy/health {
		header * {
			Cache-Control "no-store, max-age=0"
		}
		php_server
	}
<!-- END BLOCK: health -->
<!-- START BLOCK: worker -->
	php_server{$php_matcher} {
		worker {$document_root}/index.php
	}
<!-- END BLOCK: worker -->
<!-- START BLOCK: standard -->
	php_server{$php_matcher}
<!-- END BLOCK: standard -->
}

<!-- END BLOCK: site -->
